version: 0.2
phases:
  install:
    commands:
      # Install aws cdk
      - npm install -g aws-cdk
      # Installs the dependencies as defined by the `requirements.txt` file
      # present in the root directory of the package
      - pip install -r requirements.txt
  build:
    commands:
      # Builds the CDK App so it can be synthesized
      - cdk synth
      # Synthesizes the CDK App and puts the resulting artifacts into `dist`
      - cdk synth -- -o dist
artifacts:
  # The output artifact is all the files in the `dist` directory
  base-directory: dist
  files: '**/*'